name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          docker image prune -f
          docker buildx prune -f

      - name: Build Docker images
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: docker compose build

      - name: Deploy containers
        run: docker compose up -d --force-recreate
